### ISSUE TITLE
Allow option to hide retweets

### ISSUE THREAD

**Issue by ryanprior** [dialelo/turses#204]
Per request from a peer, it would be nice to have a feature enabling the user to hide retweets for a quieter reading experience.

**Comment by ryanprior** [comment]
See my related pull request [here](https://github.com/dialelo/turses/pull/205).

**Comment by b-binaohan** [comment]
when turning on this option. In the UI, when you scroll down, it crashes (instead of loading the older tweets).

**Comment by muziejus** [comment]
this would be a good feature, especially with searches. the Twitter API lets us specify `-rt` in doing a search, after all.

**Comment by ryanprior** [comment]
I fixed the issue reported above.

@muziejus my patch sets tweepy's "include_rts" flag when fetching timelines, which results in the appropriate API call to exclude retweets.

**Comment by muziejus** [comment]
Brilliant. Thanks. I added the patch, but it didn't work with searches, which was precisely where I wanted it to. I added this:

```
@to_status
@include_entities
@check_retweets
def search(self, text, **kwargs):
      return self._api.search(text, **kwargs)
```
But the RTs still show up. I'm not very familiar w/ tweepy, so I don't know if I'm doing something wrong.
